defaults: &defaults
  oauth:
    vk:
      id: '3654198'
      secret: '4mmhmh9oNVi0N6sR94f7'
    facebook:
      id: '3654198'
      secret: '4mmhmh9oNVi0N6sR94f7'
  sms:
    user: "2907_b00m"
    password: "P244w0rd"
  paysio:
    key: 'pk_8AivNdCA3oIHSWvNpyTDZr8rU6eG4OltI1DgRNt'
    secret: 'IjhH5BfD7qH2BygsnlflTj6RvvGjnXAnm2HpTn0'
  just_gateway:
    login: '102619'
    secret: '52624d7b8247a5916ed8b927560f829e'

development:
  <<: *defaults


production:
  user: billpal
  <<: *defaults

