defaults: &defaults
  oauth:
    vk:
      id: '3654198'
      secret: '4mmhmh9oNVi0N6sR94f7'
    facebook:
      id: '3654198'
      secret: '4mmhmh9oNVi0N6sR94f7'
  sms:
    user: "2907_b00m"
    password: "P244w0rd"
  paysio:
    secret: 'IjhH5BfD7qH2BygsnlflTj6RvvGjnXAnm2HpTn0'

development:
  <<: *defaults


production:
  user: billpal
  <<: *defaults

